### ISSUE TITLE
A weekly Zoom meeting agreed

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#1]
I suggest Tuesdays 14:00 CET, max 1 hour exactly.

Henk - proposal
Kor - agreed?
Jasmina - agreed?

**Comment by henkvancann** [comment]
Henk van Cann is inviting you to a weekly scheduled Zoom meeting. Start off on March 15th 2022. After a few weeks: bi-weekly.

Topic: Henk van Cann's Personal Meeting Room

Join Zoom Meeting
https://us04web.zoom.us/j/6859702250?pwd=bEwxdTB6MUhadHExemhTWTQ0VlVydz09

Meeting ID: per e-mail / signal
Passcode: per e-mail / signal

**Comment by henkvancann** [comment]
After a weekly Zoom session (that can be as brief as possible) we all work our separate ways and individual timing.

**Comment by romanova1** [comment]
Hi Henk, Tuesday at 9.30 AM works for me. Any other day of that week I can jump on a call between 9-11AM.

**Comment by kordwarshuis** [comment]
Tuesday at 9.30 AM works for me too.

**Comment by henkvancann** [comment]
Just for the first week:

Topic: Zoom Meeting Kick-off MOOC - trial
Time: Mar 15, 2022 09:30 AM Amsterdam

Join Zoom Meeting
https://us04web.zoom.us/j/6859702250?pwd=vdSs1uGxSCDK-3vh0QEmbd9rdeFtlH.1

Meeting ID:per e-mail
Passcode: per e-mail
