### ISSUE TITLE
Introductory text on Moodle install / app submitted

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#11]
"MOOC-trials" heading
"Key management is key to asset security and sovereign identifiers" sub heading

Introduction: "We'd like people to self-educate themselves on their smartphone. The reward is life-time skills."

<img width="547" alt="Keri_logo_color_on_white" src="https://user-images.githubusercontent.com/479356/159453442-255f7c33-83d8-454a-a7c5-98013dd9538e.png">.  (you might have to create your own gif version of the logo by making the white background transparent. If you do so, please attach the result here too :), I am interested)

The current connected building blocks banner is great for the time being.

**Comment by kordwarshuis** [comment]
An SVG version would be nice too. Maybe the creator has these?

**Comment by romanova1** [comment]
<img width="280" alt="159453442-255f7c33-83d8 (2)" src="https://user-images.githubusercontent.com/36804362/159880491-2db6df98-70d9-45a5-b6f3-e4e4f418a24c.png">
I uploaded the logo on Tuesday. I'm sending you the version with the transparent background I used.
