### ISSUE TITLE
Hosting provider upgrade server space

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#15]
@kordwarshuis Could you gather some info for me to address our hosting provider ? What I need is : links to online server active storage (database) space that either have fixed prices that are much lower or variable costs that are negligible.

**Comment by kordwarshuis** [comment]
I have asked the current provider about pricing, compared to competitors.

**Comment by kordwarshuis** [comment]
I have sent more info to the hosting provider and waiting for a reply.

**Comment by henkvancann** [comment]
I saw a question about concurrent users of quizzes and courses in the mail. There are not many concurrent users for the course itself will be self study on third party websites and will not run through our Moodle install. It's just the default space a new Moodle user occupies in relation to the high drop out rate.

**Comment by kordwarshuis** [comment]
I have passed this info to hosting provider.

**Comment by kordwarshuis** [comment]
The hosting provider has made an offer.

**Comment by henkvancann** [comment]
Accepted offer and continued in https://servicedesk.digistate.nl/nl/tickets/view/DS30013
