### ISSUE TITLE
Look at Duolingo app for inspiration

### ISSUE THREAD

**Issue by kordwarshuis** [henkvancann/MOOC-trials#18]
-“Three day streak”
-Set a goal for yourself
-Get an e-mail after a while when you're inactive (“Duolingo is very sad”)
-Beautiful and easy User Interface
-Very visual and audio
Etc

Information taken from own experience and also:
https://www.duolingo.com
https://www.youtube.com/watch?v=SBjeXF_Osm4

**Comment by henkvancann** [comment]
@romanova1 wrote in Signal: I found a plugin with similar purpose: https://moodle.org/plugins/mod_reengagement

**Comment by kordwarshuis** [comment]
Won't fix.
