### ISSUE TITLE
Add 2 roles for 2 individual users

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#20]
Teacher and course creator roles. See Signal and search for

"@Jasmina R New users"

to find the e-mail addresses you can creator these roles for.

**Comment by romanova1** [comment]
Martijntjuh11@live.nl is added as a course creator. Once he creates a course, I can assign you as a teacher.

Please send me another email for you to add you as a course creator, one of the emails provided is used for the main admin account.
