### ISSUE TITLE
#21 Questions-Part-1 

### ISSUE THREAD

**Issue by MH1104** [henkvancann/MOOC-trials#21]
**1. Link to google sheet:** https://docs.google.com/spreadsheets/d/1Xl9Hb5PdLR-0twbq9bRVd9mMa0ZDcBECAUf0fSd3sYs/edit?usp=sharing

**2. References/Source of the questions:** https://data-flair.training/blogs/blockchain-quiz-test-knowledge/

**3. Questions**
To keep the questions private, @henkvancann has moved them to:
https://hackmd.io/R3_ad0cOQyCseewIKoATKQ

@MH1104 if you'd like to edit them there, create a hackmd.io account and be able to edit.

**Comment by MH1104** [comment]
Updated and added some more questions let me know what you think about the new ones. @henkvancann

**Comment by henkvancann** [comment]
done
