### ISSUE TITLE
Acceptable filetypes unclear to course creator role

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#22]
<img width="873" alt="Screenshot 2022-04-07 at 18 08 40" src="https://user-images.githubusercontent.com/479356/162248575-42c31f54-2c97-49fe-9668-18d1dbded30b.png">

The user interface of the Moodle back end does not tell you upfront which file types are ok to upload.
And when you try, even the most common type fails: pdf.

Path: https://keri.blockchainbird.org/contentbank/index.php?contextid=1 -> upload -> choose a file 

I logged in as course creator.

Question: how can a back end user know which file types are acceptable by the system and does this need to be configured?

**Comment by romanova1** [comment]
Please try again mow
