### ISSUE TITLE
Registered for the mobile app software

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#8]
Related issue: Apply as a NGO  https://github.com/henkvancann/MOOC-trials/issues/16
Send API-key to Moodle expert

**Comment by henkvancann** [comment]
https://apps.moodle.com/local/apps/

**Comment by henkvancann** [comment]
Alias moodle@bcws.io -> jasmina3108@yahoo.com, hvancann@bcws.io has been created

**Comment by henkvancann** [comment]
<meta name="moodle-validation" content="{pasted in Signal group today}">

**Comment by henkvancann** [comment]
@romanova1 you can close this issue when the Moodle validation has been completed.

**Comment by henkvancann** [comment]
Has the Moodle validation been completed? If so, pls close the issue

**Comment by romanova1** [comment]
I don't know. I added the code you've sent me. We are still having the free plan with limitations.
![Screenshot 2022-04-08 124011](https://user-images.githubusercontent.com/36804362/162420197-b7149923-c687-4615-b15b-fb0054eeffec.png)

**Comment by henkvancann** [comment]
Even the free plan should be validated I think?

IMG DELETED

<meta name="moodle-validation" content="1d1c221b84e7c7396edb79a2d4ebc649">

**Comment by romanova1** [comment]
What happens when you click Validate?

**Comment by romanova1** [comment]
How can I see the page from the screenshot?

**Comment by henkvancann** [comment]
Sometimes live is so easy.

<img width="1091" alt="Screenshot 2022-04-11 at 23 36 51" src="https://user-images.githubusercontent.com/479356/162838409-358086b4-a2fe-4a6c-8e07-9217d8593621.png">
